language: php
php:
    - 7.0
    - 7.1
    - 7.2

install:
    - composer install
    - composer require satooshi/php-coveralls --dev
    - composer run-script post-create-project-cmd

script:
    - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
